@extends('layouts.admin')
@section('title','รายงาน')
@section('content')
@php $statusLabels=\App\Models\Order::statusLabels(); @endphp
<div class="d-flex justify-content-between align-items-center mb-4">
    <div><h3 class="fw-bold mb-1">รายงานภาพรวมเว็บไซต์</h3><div class="text-muted">สรุปยอดขาย สินค้า ลูกค้า การชำระเงิน สต๊อก และใบเสร็จ</div></div>
    <div class="d-flex gap-2"><button class="btn btn-outline-secondary rounded-pill" onclick="window.print()"><i class="bi bi-printer"></i> พิมพ์รายงาน</button><button class="btn btn-admin rounded-pill" onclick="exportTableToCSV('report.csv')"><i class="bi bi-file-earmark-spreadsheet"></i> Export CSV</button></div>
</div>
<form method="get" class="content-card p-3 mb-4"><div class="row g-2 align-items-end"><div class="col-md-3"><label class="form-label">ช่วงเวลา</label><select name="range" class="form-select rounded-pill"><option value="today" @selected($range==='today')>วันนี้</option><option value="7" @selected($range==='7')>7 วันล่าสุด</option><option value="30" @selected($range==='30')>30 วันล่าสุด</option><option value="custom" @selected($range==='custom')>กำหนดเอง</option></select></div><div class="col-md-3"><label class="form-label">จากวันที่</label><input type="date" name="from" value="{{optional($from)->format('Y-m-d')}}" class="form-control rounded-pill"></div><div class="col-md-3"><label class="form-label">ถึงวันที่</label><input type="date" name="to" value="{{optional($to)->format('Y-m-d')}}" class="form-control rounded-pill"></div><div class="col-md-3"><button class="btn btn-admin rounded-pill w-100">แสดงรายงาน</button></div></div></form>
<div class="row g-3 mb-4">
    <div class="col-md-4 col-xl-2"><div class="content-card metric-card p-3 h-100"><div class="text-muted small">ยอดขาย</div><h4 class="fw-bold text-danger mb-0">฿{{number_format($sales,2)}}</h4></div></div>
    <div class="col-md-4 col-xl-2"><div class="content-card p-3 h-100"><div class="text-muted small">คำสั่งซื้อ</div><h4 class="fw-bold mb-0">{{number_format($orders)}}</h4></div></div>
    <div class="col-md-4 col-xl-2"><div class="content-card p-3 h-100"><div class="text-muted small">สินค้าที่ขาย</div><h4 class="fw-bold mb-0">{{number_format($itemsSold)}}</h4></div></div>
    <div class="col-md-4 col-xl-2"><div class="content-card p-3 h-100"><div class="text-muted small">ค่าจัดส่ง</div><h4 class="fw-bold mb-0">฿{{number_format($shipping,2)}}</h4></div></div>
    <div class="col-md-4 col-xl-2"><div class="content-card p-3 h-100"><div class="text-muted small">ต้นทุนรวม</div><h4 class="fw-bold mb-0">฿{{number_format($costTotal,2)}}</h4></div></div>
    <div class="col-md-4 col-xl-2"><div class="content-card metric-card p-3 h-100"><div class="text-muted small">กำไรขั้นต้น</div><h4 class="fw-bold text-success mb-0">฿{{number_format($grossProfit,2)}}</h4></div></div>
</div>
<div class="row g-3">
    <div class="col-lg-7"><div class="content-card p-4 h-100"><h5 class="fw-bold mb-3">รายงานสินค้าขายดี Top 10</h5><div class="table-responsive"><table class="table align-middle report-table"><thead class="table-light"><tr><th>สินค้า</th><th>จำนวนขาย</th><th class="text-end">รายได้</th></tr></thead><tbody>@forelse($bestProducts as $p)<tr><td>{{$p->product_name}}</td><td>{{$p->qty}}</td><td class="text-end text-danger fw-bold">฿{{number_format($p->revenue,2)}}</td></tr>@empty<tr><td colspan="3" class="text-center text-muted">ยังไม่มีข้อมูล</td></tr>@endforelse</tbody></table></div></div></div>
    <div class="col-lg-5"><div class="content-card p-4 h-100"><h5 class="fw-bold mb-3">รายงานสต๊อกสินค้าใกล้หมด</h5><div class="table-responsive"><table class="table align-middle"><thead class="table-light"><tr><th>SKU</th><th>สินค้า</th><th class="text-center">คงเหลือ</th></tr></thead><tbody>@forelse($lowStockItems as $i)<tr><td>{{$i->product->sku ?? '-'}}</td><td>{{$i->product->name ?? '-'}}</td><td class="text-center text-danger fw-bold">{{$i->quantity}}</td></tr>@empty<tr><td colspan="3" class="text-center text-muted">ไม่มีสินค้าใกล้หมด</td></tr>@endforelse</tbody></table></div><a href="{{route('admin.inventory.index',['low_stock'=>1])}}" class="btn btn-outline-warning rounded-pill">ดูสินค้าใกล้หมดทั้งหมด</a></div></div>
</div>
<div class="row g-3 mt-1">
    <div class="col-lg-4"><div class="content-card p-4 h-100"><h5 class="fw-bold mb-3">รายงานลูกค้า</h5>@forelse($topCustomers as $c)<div class="d-flex justify-content-between border-bottom py-2"><span>{{$c->user->name ?? '-'}}</span><span><b>{{$c->order_count}}</b> ออเดอร์ / ฿{{number_format($c->spending,2)}}</span></div>@empty<div class="text-muted">ยังไม่มีข้อมูล</div>@endforelse</div></div>
    <div class="col-lg-4"><div class="content-card p-4 h-100"><h5 class="fw-bold mb-3">รายงานการชำระเงิน</h5>@forelse($paymentMethods as $m)<div class="d-flex justify-content-between border-bottom py-2"><span>{{['qr'=>'QR Code','bank_transfer'=>'โอนธนาคาร','cod'=>'เก็บเงินปลายทาง'][$m->method] ?? $m->method}}</span><span><b>{{$m->count}}</b> รายการ</span></div>@empty<div class="text-muted">ยังไม่มีข้อมูล</div>@endforelse</div></div>
    <div class="col-lg-4"><div class="content-card p-4 h-100"><h5 class="fw-bold mb-3">รายงานสถานะคำสั่งซื้อ</h5>@foreach($statusLabels as $key=>$label)<div class="d-flex justify-content-between border-bottom py-2"><span>{{$label}}</span><b>{{(int)($orderStatusCounts[$key] ?? 0)}}</b></div>@endforeach</div></div>
</div>
<div class="content-card p-4 mt-4"><h5 class="fw-bold mb-3">รายงานใบเสร็จล่าสุด</h5><div class="table-responsive"><table class="table align-middle"><thead class="table-light"><tr><th>เลขที่ใบเสร็จ</th><th>เลขออเดอร์</th><th>ลูกค้า</th><th class="text-end">ยอดเงิน</th><th></th></tr></thead><tbody>@foreach($receiptOrders as $o)<tr><td>RC{{$o->created_at->format('Ymd')}}{{str_pad($o->id,5,'0',STR_PAD_LEFT)}}</td><td>{{$o->order_number}}</td><td>{{$o->user->name ?? '-'}}</td><td class="text-end text-danger fw-bold">฿{{number_format($o->total,2)}}</td><td class="text-end"><a class="btn btn-sm btn-outline-success rounded-pill" href="{{route('receipts.show',$o)}}">ดูใบเสร็จ</a></td></tr>@endforeach</tbody></table></div></div>
<script>function exportTableToCSV(filename){let rows=[...document.querySelectorAll('.report-table tr')].map(r=>[...r.children].map(c=>'"'+c.innerText.replaceAll('"','""')+'"').join(','));let blob=new Blob([rows.join('\n')],{type:'text/csv;charset=utf-8;'});let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=filename;a.click();}</script>
<style>@media print{.admin-sidebar,.admin-topbar,form,.btn{display:none!important}.content-card{box-shadow:none!important;border:1px solid #ddd}}</style>
@endsection
