<!doctype html><html lang="th"><head><meta charset="utf-8"><style>
@page{size:A4;margin:0}body{font-family:DejaVu Sans,sans-serif;color:#111827;margin:0}.receipt-a4{width:210mm;min-height:297mm;background:#fff;padding:10mm;box-sizing:border-box}.receipt-header-v2{display:table;width:100%;border-bottom:1px solid #cbd5e1;padding-bottom:10px}.logo-panel{display:table-cell;width:22%;text-align:center;vertical-align:top}.company-panel{display:table-cell;width:46%;font-size:10px;vertical-align:top}.receipt-header-v2>div:nth-child(3){display:table-cell;width:32%;vertical-align:top}.doc-title-v2{font-size:18px;line-height:1.15;font-weight:bold;text-align:center;margin:0 0 6px;color:#13231f}.doc-info-v2{background:#e6f7d8;border-radius:8px;padding:8px;font-size:10px}.receipt-logo-v2{max-width:90px;max-height:70px}.logo-title{display:none}.logo-sub{display:none}.company-panel h1{display:none}.company-name{font-weight:bold}.buyer-box-v2{font-size:10px;margin:12px 0}.buyer-box-v2 h3{margin:0 0 6px;color:#d92d3a}.buyer-grid{display:table;width:100%;margin-bottom:4px}.buyer-grid div{display:table-cell;width:25%}.items-table{width:100%;border-collapse:collapse;margin-top:10px;font-size:9px}.items-table th{background:#e6f7d8;text-align:left;padding:6px;border:1px solid #e5e7eb}.items-table td{padding:6px;border:1px solid #e5e7eb}.right{text-align:right}.center{text-align:center}.summary-section-v2{display:table;width:100%;border-top:1px solid #cbd5e1;border-bottom:1px solid #cbd5e1;margin-top:15px;padding:8px 0}.summary-left-v2{display:table-cell;width:58%;font-size:10px;vertical-align:top}.summary-total-box-v2{display:table-cell;width:42%;background:#e6f7d8;border-radius:8px;padding:9px;font-size:10px;vertical-align:top}.summary-left-v2 h3{margin:0 0 5px;color:#d92d3a}.summary-row{display:table;width:100%;margin:3px 0}.summary-row b{display:table-cell}.summary-row span{display:table-cell;text-align:right}.summary-total-box-v2 .amount{font-size:16px;font-weight:bold;color:#27316c;text-align:right}.payment-note-v2{border-bottom:1px solid #cbd5e1;padding:8px 0;font-size:10px}.signature-section-v2{display:table;width:100%;margin-top:14px;font-size:9px}.signature-box-v2{display:table-cell;width:50%;text-align:center;vertical-align:top}.sig-title{font-weight:bold;color:#d92d3a;margin-bottom:6px}.stamp-area{height:42px;border:1px dashed #cbd5e1;color:#94a3b8;text-align:center;line-height:42px;margin:0 auto 6px;width:110px}.sign-line{height:24px;border-bottom:1px solid #94a3b8;margin:0 auto 6px;width:65%}.fine-print{text-align:center;font-size:8px;color:#64748b;margin-top:10px}.text-baht{color:#64748b;text-align:right}.total-line,.pay-line{color:#d92d3a;font-weight:bold}

.receipt-header-v2.compact-header{display:table!important;width:100%;border-bottom:1px solid #cbd5e1;padding-bottom:10px}.company-under-logo{display:table-cell!important;width:52%!important;text-align:left!important;vertical-align:top!important;padding-right:12px!important}.company-under-logo .receipt-logo-v2{display:block;max-width:80px!important;max-height:60px!important;margin:0 0 4px 0}.company-info-lines{font-size:8.5px;line-height:1.35;white-space:normal;word-break:normal;overflow-wrap:break-word}.company-info-lines .company-name{font-size:10.5px!important;line-height:1.2;white-space:normal;margin-bottom:1px;overflow-wrap:break-word}.company-info-lines .company-subtitle{font-size:8.5px;font-weight:bold;white-space:normal;margin-bottom:3px;overflow-wrap:break-word}.doc-right-panel{display:table-cell!important;width:48%!important;text-align:right!important;vertical-align:top!important}.doc-title-v2.single-line-title{font-size:19px!important;white-space:nowrap;text-align:right!important;line-height:1.1;margin-bottom:6px}.doc-info-v2{text-align:left;display:inline-block;min-width:210px;font-size:8.5px}.clean-signatures .sign-line{height:28px;border-bottom:1px solid #111;margin:14px auto 6px;max-width:180px}.clean-signatures .sig-title{color:#111!important}.clean-signatures .small-muted{color:#111;font-size:8.5px}
</style>
<style>
.receipt-header-v2.compact-header{grid-template-columns:minmax(0,1fr) minmax(300px,0.85fr);gap:24px;align-items:start}.company-under-logo{text-align:left}.company-under-logo .receipt-logo-v2{max-width:150px;max-height:90px;object-fit:contain}.company-under-logo .company-name{font-size:1.05rem;font-weight:900;color:#14533f;line-height:1.25}.company-under-logo .company-subtitle{font-weight:700}.single-line-title{white-space:nowrap;font-size:2.2rem!important;line-height:1.15}.doc-title-center{text-align:center}.clean-signatures .signature-box-v2{border:0;background:transparent;padding:0;text-align:center}.clean-signatures .stamp-area{display:none}.clean-signatures .sign-line{height:48px;border-bottom:1px dotted #9ca3af;margin:28px auto 10px;max-width:260px}.small-muted{color:#6b7280;font-size:.95rem}
@media print{.single-line-title{font-size:1.9rem!important}.company-under-logo .receipt-logo-v2{max-width:120px}.receipt-header-v2.compact-header{gap:16px}}
</style>
<style>
.company-address-line{display:flex;align-items:flex-start;gap:6px;white-space:normal;overflow-wrap:break-word;word-break:normal;max-width:100%;}
.company-address-line .receipt-icon{flex:0 0 auto;white-space:nowrap;}
.company-address-line span:last-child{min-width:0;overflow-wrap:break-word;}
@media print{.company-address-line{gap:4px;}}
</style>

</head><body>@include('receipts._receipt_body')</body></html>
